#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

CC = gcc.exe
CXX = g++.exe
AR = ar.exe
LD = g++.exe
WINDRES = windres.exe

INC = 
CFLAGS = -Wall -fexceptions
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj\\Debug
DEP_DEBUG = 
OUT_DEBUG = bin\\Debug\\TDP2_CodeBlocks.exe

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj\\Release
DEP_RELEASE = 
OUT_RELEASE = bin\\Release\\TDP2_CodeBlocks.exe

OBJ_DEBUG = $(OBJDIR_DEBUG)\\driver.o $(OBJDIR_DEBUG)\\request.o $(OBJDIR_DEBUG)\\room.o $(OBJDIR_DEBUG)\\semester.o

OBJ_RELEASE = $(OBJDIR_RELEASE)\\driver.o $(OBJDIR_RELEASE)\\request.o $(OBJDIR_RELEASE)\\room.o $(OBJDIR_RELEASE)\\semester.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	cmd /c if not exist bin\\Debug md bin\\Debug
	cmd /c if not exist $(OBJDIR_DEBUG) md $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)\\driver.o: driver.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c driver.cpp -o $(OBJDIR_DEBUG)\\driver.o

$(OBJDIR_DEBUG)\\request.o: request.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c request.cpp -o $(OBJDIR_DEBUG)\\request.o

$(OBJDIR_DEBUG)\\room.o: room.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c room.cpp -o $(OBJDIR_DEBUG)\\room.o

$(OBJDIR_DEBUG)\\semester.o: semester.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c semester.cpp -o $(OBJDIR_DEBUG)\\semester.o

clean_debug: 
	cmd /c del /f $(OBJ_DEBUG) $(OUT_DEBUG)
	cmd /c rd bin\\Debug
	cmd /c rd $(OBJDIR_DEBUG)

before_release: 
	cmd /c if not exist bin\\Release md bin\\Release
	cmd /c if not exist $(OBJDIR_RELEASE) md $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)\\driver.o: driver.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c driver.cpp -o $(OBJDIR_RELEASE)\\driver.o

$(OBJDIR_RELEASE)\\request.o: request.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c request.cpp -o $(OBJDIR_RELEASE)\\request.o

$(OBJDIR_RELEASE)\\room.o: room.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c room.cpp -o $(OBJDIR_RELEASE)\\room.o

$(OBJDIR_RELEASE)\\semester.o: semester.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c semester.cpp -o $(OBJDIR_RELEASE)\\semester.o

clean_release: 
	cmd /c del /f $(OBJ_RELEASE) $(OUT_RELEASE)
	cmd /c rd bin\\Release
	cmd /c rd $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

